import type { Metadata } from "next";

// import "../global.css";
import { ThemeProvider } from "@/components/theme-provider";
import Dashboard from "@/components/dash";



export const metadata: Metadata = {
  title: "JoinLinkUp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
            <body className="bg-white dark:bg-black">
             
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
           <Dashboard/>
            
            {children}
          </ThemeProvider>
  
        </body>
    </html>
  );
}
