import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/small";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "JoinLinkUp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
            <body className="bg-white dark:bg-black">
             
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
             <Navbar />
            
            {children}
          </ThemeProvider>
  
        </body>
    </html>
  );
}
